#!/bin/bash
# =============================================================================
# Guide de création du dépôt Git pour le projet
# =============================================================================
#
# INSTRUCTIONS À SUIVRE SUR VOTRE MACHINE LOCALE
#
# =============================================================================

echo "=== ÉTAPE 1: Configuration Git (une seule fois) ==="
echo ""
echo "Si vous n'avez jamais configuré Git, exécutez :"
echo ""
echo "  git config --global user.name \"Votre Nom\""
echo "  git config --global user.email \"votre.email@etu.univ-cotedazur.fr\""
echo ""

echo "=== ÉTAPE 2: Initialiser le dépôt local ==="
echo ""
echo "Naviguez vers le dossier du projet et initialisez Git :"
echo ""
echo "  cd ~/projet-archi-hpc"
echo "  git init"
echo "  git add ."
echo "  git commit -m \"Initial commit: structure du projet HPC\""
echo ""

echo "=== ÉTAPE 3: Créer le dépôt sur GitHub ==="
echo ""
echo "Option A - Via le site web GitHub :"
echo "  1. Allez sur https://github.com"
echo "  2. Cliquez sur '+' puis 'New repository'"
echo "  3. Nom: projet-archi-hpc"
echo "  4. Visibilité: Private (recommandé)"
echo "  5. Ne PAS cocher 'Add README' (on en a déjà un)"
echo "  6. Cliquez 'Create repository'"
echo ""
echo "Option B - Via GitHub CLI (si installé) :"
echo "  gh repo create projet-archi-hpc --private --source=. --push"
echo ""

echo "=== ÉTAPE 4: Lier et pousser vers GitHub ==="
echo ""
echo "Après avoir créé le dépôt sur GitHub :"
echo ""
echo "  git remote add origin https://github.com/VOTRE_USERNAME/projet-archi-hpc.git"
echo "  git branch -M main"
echo "  git push -u origin main"
echo ""

echo "=== COMMANDES GIT UTILES ==="
echo ""
echo "Voir l'état des fichiers :"
echo "  git status"
echo ""
echo "Ajouter des modifications :"
echo "  git add ."
echo "  git commit -m \"Description des modifications\""
echo "  git push"
echo ""
echo "Voir l'historique :"
echo "  git log --oneline"
echo ""

echo "=== STRUCTURE DES COMMITS RECOMMANDÉE ==="
echo ""
echo "Après chaque étape importante, faites un commit :"
echo ""
echo "  # Après avoir terminé l'exercice 1"
echo "  git add exercice1/"
echo "  git commit -m \"Exercice 1: benchmark détection taille cache\""
echo ""
echo "  # Après avoir terminé l'exercice 2"
echo "  git add exercice2/"
echo "  git commit -m \"Exercice 2: benchmark bande passante mémoire\""
echo ""
echo "  # Après avoir terminé l'exercice 5"
echo "  git add exercice5/"
echo "  git commit -m \"Exercice 5: utilisation de Calibrator\""
echo ""
echo "  # Après avoir rédigé le rapport"
echo "  git add rapport/"
echo "  git commit -m \"Rapport: rédaction complète\""
echo ""
